## R Markdown

```{r pressure, echo=FALSE}
install.packages("ggpubr")
install.packages("FSA")
```

```{r pressure, echo=FALSE}
library(ggplot2)
library(vegan)
library(FSA)
library(showtext)
```

```{r pressure, echo=FALSE}
filename="filename.csv"
attenuation=read.csv(filename)
exceldata = attenuation 
dfdata = data.frame(exceldata)
dfdata
```

```{r pressure, echo=FALSE}
font_add(family="Arial", regular="Arial.ttf")
showtext_auto()
dfdata$Converter <- factor(dfdata$Converter,levels = c("Non","High"))
pdf('filename.pdf', width = 4, height=4)
ggplot(dfdata, aes(x=Converter, y=Sulf, fill=Converter)) + 
    geom_boxplot(width=0.5) + theme_classic()+ scale_fill_brewer(palette="BrBG") + theme(text = element_text(family="Arial", size = 12), axis.text=element_text(family="Arial", size=12), axis.title=element_text(family="Arial", size=12)) + theme(legend.position = "none") + ylab("Sulfated (umol/g)")
```

```{r pressure, echo=FALSE}
filename="filename.csv"
norm=read.csv(filename)
exceldata = norm 
dfdata = data.frame(exceldata)
dfdata
shapiro.test(dfdata$Sulf)
#so data not normal since p<0.05
```

```{r pressure, echo=FALSE}
mw= wilcox.test(Sulfation ~ Converter, data=dfdata)
mw
```

```{r pressure, echo=FALSE}
mw=t.test(Secondary ~ Converter, data=dfdata)
mw
```
