## R Markdown

```{r pressure, echo=FALSE}
install.packages("ggpubr")
install.packages("FSA")
install.packages("ggbeeswarm")
```

```{r pressure, echo=FALSE}
library(ggplot2)
library(vegan)
library(FSA)
library(ggbeeswarm)
library(ggpubr)
library(showtext)
```

```{r pressure, echo=FALSE}
filename="filename.csv"
attenuation=read.csv(filename)
exceldata = attenuation 
dfdata = data.frame(exceldata)
dfdata
```
```{r pressure, echo=FALSE}
font_add(family="Arial", regular="Arial.ttf")
showtext_auto()
dfdata$Conversion <- factor(dfdata$Conversion,levels = c("Non", "High"))
dfdata$Bacteria <- factor(dfdata$Bacteria,levels = c("B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10"))
pdf('filename.pdf', width = 4, height=4)
ggplot(dfdata, aes(x=Bacteria, y=Relative, fill=Conversion)) + 
    geom_boxplot(width=0.5) + theme_classic()+ scale_fill_brewer(palette="BrBG") + theme(text = element_text(family="Arial", size = 12), axis.text=element_text(family="Arial", size=12), axis.title=element_text(family="Arial", size=12)) + ylab("Relative Abundance")
```

```{r pressure, echo=FALSE}
filename="filename.csv"
norm=read.csv(filename)
exceldata = norm 
dfdata = data.frame(exceldata)
dfdata
shapiro.test(dfdata$Abundance)
#so data not normal since p<0.05
```

```{r pressure, echo=FALSE}
filename="attenuation.csv"
attenuation=read.csv(filename)
exceldata = attenuation 
dfdata = data.frame(exceldata)
dfdata
```

```{r pressure, echo=FALSE}
mw= kruskal.test(Abundance ~ Conversion, data=dfdata)
mw
```
```{r pressure, echo=FALSE}
mw=dunnTest(Abundance ~ Conversion, data=dfdata, method="bh")
mw
```
```{r pressure, echo=FALSE}
one.way=aov(Abundance ~ Conversion, data=dfdata)
summary(one.way)
```
```{r pressure, echo=FALSE}
TukeyHSD(one.way, which = "Conversion")
```

```{r pressure, echo=FALSE}
mw= wilcox.test(Sulf ~ Converter, data=dfdata)
mw
```

```{r pressure, echo=FALSE}
mw=t.test(Sec ~ Converter, data=dfdata)
mw
```


