## R Markdown

```{r pressure, echo=FALSE}
install.packages("ggpubr")
install.packages("tidyverse")
install.packages("broom")
```

```{r pressure, echo=FALSE}
library(ggplot2)
library(vegan)
library(FSA)
```

```{r pressure, echo=FALSE}
filename="filename.csv"
attenuation=read.csv(filename)
dfdata = data.frame(attenuation)
dfdata
```

```{r pressure, echo=FALSE}
dfdata$Time <- factor(dfdata$Time,levels = c("48", "72"))
dfdata$Group <- factor(dfdata$Group,levels = c("NC", "0%", "NC-10", "10%", "NC-20","20%","NC-40", "40%"))
z="Group"
pdf('Cop3.pdf', width = 4, height=4)
ggplot(dfdata, aes(x=Time, y=Coprostanol, fill=Group)) + 
    geom_col(width = 0.7, position = position_dodge(0.9)) + theme_classic() + scale_fill_brewer(palette="YlGnBu") 
```

```{r pressure, echo=FALSE}
dfdata$Time <- factor(dfdata$Time,levels = c("48", "72"))
dfdata$Group <- factor(dfdata$Group,levels = c("NC", "0%", "NC-10", "10%", "NC-20","20%","NC-40", "40%"))
z="Group"
pdf('Cop2.pdf', width = 4, height=4)
ggplot(dfdata, aes(x=Time, y=Coprostanol, fill=Group)) + 
    geom_bar(position="dodge", stat = "identity") + theme_classic() + scale_fill_brewer(palette="YlGnBu") 
```

```{r pressure, echo=FALSE}
filename="Sterols_cop.csv"
norm=read.csv(filename)
exceldata = norm 
dfdata = data.frame(exceldata)
dfdata
shapiro.test(dfdata$Coprostanol)
#so data not normal since p<0.05
```

```{r pressure, echo=FALSE}
mw= kruskal.test(Coprostanol ~ Group, data=dfdata)
mw
```

```{r pressure, echo=FALSE}
pairwise.wilcox.test(dfdata$Cholesterol, dfdata$Group,
                 p.adjust.method = "BH")
```

```{r pressure, echo=FALSE}
mw= wilcox.test(Coprostanol ~ Group, data=dfdata)
mw
```

```{r pressure, echo=FALSE}
mw=t.test(Coprostanol~ Group, data=dfdata)
mw
```


```{r pressure, echo=FALSE}
summary.aov(res.man)
```

```{r pressure, echo=FALSE}
dunnTest(Coprostanol ~ Group,
         data=dfdata,
         method="bh")
```
